use serde::{Deserialize, Serialize};
use std::str::FromStr;

/// Samsung device model entry in the FRP compatibility database
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SamsungModel {
    /// Model code e.g. "SM-A055F"
    pub model_code: String,
    /// Marketing name e.g. "Galaxy A05"
    pub marketing_name: String,
    /// Chipset family
    pub chipset: String,
    /// Supported Android versions
    pub android_versions: Vec<String>,
    /// FRP bypass methods that work on this device
    pub supported_methods: Vec<FrpMethod>,
    /// Minimum security patch where methods stop working
    pub max_security_patch: Option<String>,
    /// Notes / caveats
    pub notes: Option<String>,
    /// Whether ADB must be pre-authorized (debugging previously enabled)
    pub requires_preauthorized_adb: bool,
    /// Whether the device supports Samsung Download Mode
    pub supports_download_mode: bool,
    /// Whether combination firmware is available for this model
    pub combination_firmware_available: bool,
}

/// FRP bypass method identifier
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub enum FrpMethod {
    /// Disable setup wizard packages via pm disable
    SetupWizardDisable,
    /// Set device provisioned flags via settings put
    DeviceProvisioning,
    /// Content provider URI manipulation to skip setup
    ContentProviderBypass,
    /// Uninstall setup wizard packages for user 0
    SetupWizardUninstall,
    /// Launch Samsung browser to download FRP bypass APK
    BrowserDownloadBypass,
    /// Launch Google Account Manager activity directly
    AccountManagerLaunch,
    /// Samsung emergency dialer + notification method
    EmergencyDialerBypass,
    /// Samsung TalkBack accessibility exploit
    TalkBackBypass,
    /// Samsung Sim Card + PIN method
    SimPinBypass,
    /// Combination firmware flash via Download Mode (requires Odin)
    CombinationFirmware,
    /// Alliance Shield / Knox bypass
    AllianceShieldBypass,
    /// HacKTM method
    HacktmBypass,
    /// Samsung Smart Switch trick
    SmartSwitchBypass,
    /// Helper: Open Samsung Settings via ADB
    SettingsAccess,
    /// Helper: Launch QuickShortcutMaker via browser
    QuickShortcutMaker,
}

impl FrpMethod {
    pub fn id(&self) -> &str {
        match self {
            FrpMethod::SetupWizardDisable => "setup_wizard_disable",
            FrpMethod::DeviceProvisioning => "device_provisioning",
            FrpMethod::ContentProviderBypass => "content_provider_bypass",
            FrpMethod::SetupWizardUninstall => "setup_wizard_uninstall",
            FrpMethod::BrowserDownloadBypass => "browser_download_bypass",
            FrpMethod::AccountManagerLaunch => "account_manager_launch",
            FrpMethod::EmergencyDialerBypass => "emergency_dialer_bypass",
            FrpMethod::TalkBackBypass => "talkback_bypass",
            FrpMethod::SimPinBypass => "sim_pin_bypass",
            FrpMethod::CombinationFirmware => "combination_firmware",
            FrpMethod::AllianceShieldBypass => "alliance_shield_bypass",
            FrpMethod::HacktmBypass => "hacktm_bypass",
            FrpMethod::SmartSwitchBypass => "smart_switch_bypass",
            FrpMethod::SettingsAccess => "settings_access",
            FrpMethod::QuickShortcutMaker => "quick_shortcut_maker",
        }
    }

    pub fn label(&self) -> &str {
        match self {
            FrpMethod::SetupWizardDisable => "Setup Wizard Disable",
            FrpMethod::DeviceProvisioning => "Device Provisioning Flags",
            FrpMethod::ContentProviderBypass => "Content Provider Bypass",
            FrpMethod::SetupWizardUninstall => "Setup Wizard Uninstall",
            FrpMethod::BrowserDownloadBypass => "Browser Download Bypass",
            FrpMethod::AccountManagerLaunch => "Account Manager Launch",
            FrpMethod::EmergencyDialerBypass => "Emergency Dialer Bypass",
            FrpMethod::TalkBackBypass => "TalkBack Accessibility Bypass",
            FrpMethod::SimPinBypass => "SIM PIN Bypass",
            FrpMethod::CombinationFirmware => "Combination Firmware Flash",
            FrpMethod::AllianceShieldBypass => "Alliance Shield / Knox Bypass",
            FrpMethod::HacktmBypass => "HacKTM Bypass",
            FrpMethod::SmartSwitchBypass => "Smart Switch Bypass",
            FrpMethod::SettingsAccess => "Samsung Settings Access",
            FrpMethod::QuickShortcutMaker => "QuickShortcutMaker",
        }
    }

    pub fn description(&self) -> &str {
        match self {
            FrpMethod::SetupWizardDisable => 
                "Disable the Google and Samsung setup wizard packages so the device skips the Google account verification screen after factory reset. Uses 'pm disable-user --user 0'.",
            FrpMethod::DeviceProvisioning => 
                "Set device_provisioned=1 and user_setup_complete=1 via 'settings put' to mark the device as already set up, bypassing the FRP lock screen.",
            FrpMethod::ContentProviderBypass => 
                "Insert provisioning values directly into the Settings content provider URI. Works even when 'settings put' is blocked by Samsung Knox.",
            FrpMethod::SetupWizardUninstall => 
                "Uninstall (for user 0 only) the setup wizard packages. Less safe than disable but effective when disable is blocked. Preserves package data with -k flag.",
            FrpMethod::BrowserDownloadBypass => 
                "Launch Samsung Browser and open a URL to download an FRP bypass APK (e.g. FRP_Bypass.apk, QuickShortcutMaker). User then installs the APK on-device.",
            FrpMethod::AccountManagerLaunch => 
                "Directly launch the Google Account Manager intro activity to add a new Google account, which then removes the FRP lock.",
            FrpMethod::EmergencyDialerBypass => 
                "Use the emergency dialer to access Samsung's notification panel, then open settings or browser from a notification. Classic Samsung FRP method.",
            FrpMethod::TalkBackBypass => 
                "Enable TalkBack accessibility service, use its gesture-based navigation to reach the browser or settings, then proceed to add account or download bypass APK.",
            FrpMethod::SimPinBypass => 
                "Insert a SIM card with a PIN lock. The PIN prompt creates a notification that can be used to access Samsung settings or notification shade.",
            FrpMethod::CombinationFirmware => 
                "Flash Samsung Combination Firmware via Download Mode (Odin). Combination firmware disables FRP verification. Must re-flash stock firmware after. Requires PC + Odin.",
            FrpMethod::AllianceShieldBypass => 
                "Use Alliance Shield app (installed via ADB) to disable FRP-related Knox components. Works on many Exynos Samsung devices.",
            FrpMethod::HacktmBypass => 
                "Use HacKTM tool method to exploit Samsung's test mode features. Works on certain Samsung models with Android 11-13.",
            FrpMethod::SmartSwitchBypass => 
                "Connect to Samsung Smart Switch on PC while in setup wizard. Smart Switch may allow bypassing the Google verification step on older firmware.",
            FrpMethod::SettingsAccess => 
                "Open Samsung Settings app directly via ADB activity launch. From Settings, navigate to Accounts to add a Google account.",
            FrpMethod::QuickShortcutMaker => 
                "Download and launch QuickShortcutMaker via Samsung Browser. Allows opening hidden Google Account Manager activities to add/sign in to a Google account.",
        }
    }

    pub fn risk_level(&self) -> FrpRiskLevel {
        match self {
            FrpMethod::SetupWizardDisable => FrpRiskLevel::Low,
            FrpMethod::DeviceProvisioning => FrpRiskLevel::Low,
            FrpMethod::ContentProviderBypass => FrpRiskLevel::Low,
            FrpMethod::SetupWizardUninstall => FrpRiskLevel::Medium,
            FrpMethod::BrowserDownloadBypass => FrpRiskLevel::Low,
            FrpMethod::AccountManagerLaunch => FrpRiskLevel::Low,
            FrpMethod::EmergencyDialerBypass => FrpRiskLevel::Medium,
            FrpMethod::TalkBackBypass => FrpRiskLevel::Medium,
            FrpMethod::SimPinBypass => FrpRiskLevel::Low,
            FrpMethod::CombinationFirmware => FrpRiskLevel::High,
            FrpMethod::AllianceShieldBypass => FrpRiskLevel::Medium,
            FrpMethod::HacktmBypass => FrpRiskLevel::Medium,
            FrpMethod::SmartSwitchBypass => FrpRiskLevel::Low,
            FrpMethod::SettingsAccess => FrpRiskLevel::Low,
            FrpMethod::QuickShortcutMaker => FrpRiskLevel::Low,
        }
    }

    pub fn requires_download_mode(&self) -> bool {
        matches!(self, FrpMethod::CombinationFirmware)
    }

    pub fn is_adb_method(&self) -> bool {
        !self.requires_download_mode()
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub enum FrpRiskLevel {
    Low,
    Medium,
    High,
}

impl FrpRiskLevel {
    pub fn label(&self) -> &str {
        match self {
            FrpRiskLevel::Low => "Low",
            FrpRiskLevel::Medium => "Medium",
            FrpRiskLevel::High => "High",
        }
    }
}

/// The full Samsung FRP compatibility database
pub fn get_samsung_database() -> Vec<SamsungModel> {
    vec![
        // ==================== A SERIES ====================
        SamsungModel {
            model_code: "SM-A055F".into(),
            marketing_name: "Galaxy A05".into(),
            chipset: "Mediatek MT6769V/CB".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-07-01".into()),
            notes: Some("MTEK chipset. ADB must be enabled before FRP lock. TalkBack method works well on Android 13. Emergency dialer may be patched on Aug 2024+ security.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A055M".into(),
            marketing_name: "Galaxy A05 (Americas)".into(),
            chipset: "Mediatek MT6769V/CB".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-07-01".into()),
            notes: Some("Same as SM-A055F but for LATAM/USA regions.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A055S".into(),
            marketing_name: "Galaxy A05s".into(),
            chipset: "Qualcomm SM6115".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-07-01".into()),
            notes: Some("Snapdragon 680. Alliance Shield works on Exynos only — may not work here. Emergency dialer is most reliable.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A075F".into(),
            marketing_name: "Galaxy A07".into(),
            chipset: "Mediatek MT6769V/CU".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-07-01".into()),
            notes: Some("MTEK chipset. Same FRP methods as A05. ADB must be pre-enabled. TalkBack + Browser method is most reliable.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A075M".into(),
            marketing_name: "Galaxy A07 (Americas)".into(),
            chipset: "Mediatek MT6769V/CU".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-07-01".into()),
            notes: Some("Same as SM-A075F for LATAM region.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A155F".into(),
            marketing_name: "Galaxy A15 5G".into(),
            chipset: "Mediatek Dimensity 6100+".into(),
            android_versions: vec!["14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Android 14 with tougher Knox. SetupWizardUninstall may be blocked. Emergency dialer + TalkBack still work.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A155M".into(),
            marketing_name: "Galaxy A15 5G (Americas)".into(),
            chipset: "Mediatek Dimensity 6100+".into(),
            android_versions: vec!["14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Same as SM-A155F for Americas region.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A165F".into(),
            marketing_name: "Galaxy A16 5G".into(),
            chipset: "Mediatek Dimensity 6300".into(),
            android_versions: vec!["14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-10-01".into()),
            notes: Some("Newer device with Android 14. Samsung Knox is stricter. Emergency dialer and TalkBack methods still viable.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A245F".into(),
            marketing_name: "Galaxy A24".into(),
            chipset: "Mediatek Helio G99".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-07-01".into()),
            notes: Some("MTEK. Most methods work well on Android 13. Android 14 may have patches.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A346B".into(),
            marketing_name: "Galaxy A34 5G".into(),
            chipset: "Mediatek Dimensity 1080".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("MTEK Dimensity. Works with standard methods. SetupWizardUninstall may fail on Android 14.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A356B".into(),
            marketing_name: "Galaxy A35 5G".into(),
            chipset: "Exynos 1380".into(),
            android_versions: vec!["14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Exynos 1380 — Alliance Shield may work. Knox is strong on A35. Emergency dialer is the safest bet.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A546B".into(),
            marketing_name: "Galaxy A54 5G".into(),
            chipset: "Exynos 1380".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Exynos 1380. Alliance Shield works on some firmware versions. Emergency dialer method is most reliable.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-A556B".into(),
            marketing_name: "Galaxy A55 5G".into(),
            chipset: "Exynos 1480".into(),
            android_versions: vec!["14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-10-01".into()),
            notes: Some("Exynos 1480, Android 14 only. Strong Knox. Alliance Shield may work. Emergency dialer + TalkBack still viable.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },

        // ==================== M SERIES ====================
        SamsungModel {
            model_code: "SM-M115F".into(),
            marketing_name: "Galaxy M11".into(),
            chipset: "Qualcomm SDM450".into(),
            android_versions: vec!["10".into(), "11".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SmartSwitchBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-08-01".into()),
            notes: Some("Older device, most methods work. Smart Switch bypass may also work.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-M125F".into(),
            marketing_name: "Galaxy M12".into(),
            chipset: "Exynos 850".into(),
            android_versions: vec!["11".into(), "12".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SmartSwitchBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-10-01".into()),
            notes: Some("Exynos 850 — Alliance Shield works well. Very permissive FRP setup.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-M135F".into(),
            marketing_name: "Galaxy M13".into(),
            chipset: "Exynos 850".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-03-01".into()),
            notes: Some("Exynos 850. Alliance Shield works. All standard methods effective.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-M146B".into(),
            marketing_name: "Galaxy M14 5G".into(),
            chipset: "Exynos 1330".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Exynos 1330. Alliance Shield works on some builds.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-M225F".into(),
            marketing_name: "Galaxy M22".into(),
            chipset: "Mediatek Helio G80".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-03-01".into()),
            notes: Some("MTEK. Standard methods work. Older firmware is more permissive.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-M236B".into(),
            marketing_name: "Galaxy M23 5G".into(),
            chipset: "Qualcomm SM7325".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-03-01".into()),
            notes: Some("Snapdragon 750G. Alliance Shield NOT available (not Exynos). Standard methods work.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-M345F".into(),
            marketing_name: "Galaxy M34 5G".into(),
            chipset: "Exynos 1280".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Exynos 1280. Alliance Shield works on some builds. Emergency dialer is reliable.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },

        // ==================== S SERIES (FLAGSHIPS) ====================
        SamsungModel {
            model_code: "SM-S911B".into(),
            marketing_name: "Galaxy S23".into(),
            chipset: "Qualcomm SM8550-AC".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Snapdragon 8 Gen 2. Very strong Knox. Many methods patched. Emergency dialer + TalkBack still viable on older patches. Combination firmware recommended for newer patches.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-S921B".into(),
            marketing_name: "Galaxy S24".into(),
            chipset: "Exynos 2400".into(),
            android_versions: vec!["14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
                FrpMethod::CombinationFirmware,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Exynos 2400 (Global). Extremely strong Knox Guardian. ADB methods limited. Combination firmware often needed. Alliance Shield may work on some builds.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-S928B".into(),
            marketing_name: "Galaxy S24 Ultra".into(),
            chipset: "Qualcomm SM8650-AC".into(),
            android_versions: vec!["14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
                FrpMethod::CombinationFirmware,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Snapdragon 8 Gen 3. Strongest Knox. Many ADB methods patched on latest firmware. Combination firmware is the most reliable approach.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-S931B".into(),
            marketing_name: "Galaxy S25".into(),
            chipset: "Exynos 2500".into(),
            android_versions: vec!["15".into()],
            supported_methods: vec![
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::CombinationFirmware,
            ],
            max_security_patch: Some("2025-03-01".into()),
            notes: Some("Android 15, Exynos 2500. Very new device with strongest Knox yet. Most ADB methods patched. Emergency dialer + TalkBack may still work. Combination firmware recommended.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },

        // ==================== J SERIES (OLDER) ====================
        SamsungModel {
            model_code: "SM-J260F".into(),
            marketing_name: "Galaxy J2 Core".into(),
            chipset: "Exynos 7570".into(),
            android_versions: vec!["8.1".into(), "9".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SmartSwitchBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: None,
            notes: Some("Very old device (Android Go). All methods work easily. No Knox restrictions.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-J415F".into(),
            marketing_name: "Galaxy J4+".into(),
            chipset: "Qualcomm SDM450".into(),
            android_versions: vec!["9".into(), "10".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SmartSwitchBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: None,
            notes: Some("Older device. Very permissive FRP. All standard methods work without issues.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-J530F".into(),
            marketing_name: "Galaxy J5 (2017)".into(),
            chipset: "Exynos 7870".into(),
            android_versions: vec!["7.0".into(), "8.1".into(), "9".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SmartSwitchBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: None,
            notes: Some("Very old device. No FRP security. All methods work trivially.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-J737F".into(),
            marketing_name: "Galaxy J7+".into(),
            chipset: "Mediatek MT6757".into(),
            android_versions: vec!["8.1".into(), "9".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SmartSwitchBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: None,
            notes: Some("Older MTEK device. All methods work without issues.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },

        // ==================== NOTE / Z FOLD SERIES ====================
        SamsungModel {
            model_code: "SM-N960F".into(),
            marketing_name: "Galaxy Note9".into(),
            chipset: "Exynos 9810".into(),
            android_versions: vec!["9".into(), "10".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SmartSwitchBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: None,
            notes: Some("Exynos 9810. Alliance Shield works. Older device, permissive FRP. All standard methods work.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-N970F".into(),
            marketing_name: "Galaxy Note10".into(),
            chipset: "Exynos 9825".into(),
            android_versions: vec!["10".into(), "11".into(), "12".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-10-01".into()),
            notes: Some("Exynos 9825. Alliance Shield works well. Standard methods effective.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-F721B".into(),
            marketing_name: "Galaxy Z Flip4".into(),
            chipset: "Qualcomm SM8450".into(),
            android_versions: vec!["12".into(), "13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
                FrpMethod::CombinationFirmware,
            ],
            max_security_patch: Some("2024-03-01".into()),
            notes: Some("Snapdragon 8+ Gen 1. Strong Knox. Alliance Shield NOT available. Emergency dialer works. Combination firmware recommended for latest patches.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-F946B".into(),
            marketing_name: "Galaxy Z Fold5".into(),
            chipset: "Qualcomm SM8550-AC".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
                FrpMethod::CombinationFirmware,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Snapdragon 8 Gen 2. Strong Knox. Emergency dialer + TalkBack still viable. Combination firmware for latest patches.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },

        // ==================== TAB SERIES ====================
        SamsungModel {
            model_code: "SM-T505".into(),
            marketing_name: "Galaxy Tab A7 Lite".into(),
            chipset: "Mediatek MT8768T".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::SetupWizardUninstall,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SimPinBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-03-01".into()),
            notes: Some("MTEK tablet. No SIM, so SIM PIN method not applicable. All other methods work.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-X200".into(),
            marketing_name: "Galaxy Tab A9".into(),
            chipset: "Mediatek Helio G99".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("MTEK tablet. Standard methods work. No SIM slot on WiFi model.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
        SamsungModel {
            model_code: "SM-X510".into(),
            marketing_name: "Galaxy Tab S9 FE".into(),
            chipset: "Exynos 1380".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                FrpMethod::SetupWizardDisable,
                FrpMethod::DeviceProvisioning,
                FrpMethod::ContentProviderBypass,
                FrpMethod::BrowserDownloadBypass,
                FrpMethod::AccountManagerLaunch,
                FrpMethod::EmergencyDialerBypass,
                FrpMethod::TalkBackBypass,
                FrpMethod::AllianceShieldBypass,
                FrpMethod::SettingsAccess,
                FrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-06-01".into()),
            notes: Some("Exynos 1380 tablet. Alliance Shield may work. Emergency dialer reliable.".into()),
            requires_preauthorized_adb: true,
            supports_download_mode: true,
            combination_firmware_available: true,
        },
    ]
}

/// Look up a Samsung model by its model code
pub fn find_model(model_code: &str) -> Option<SamsungModel> {
    let db = get_samsung_database();
    db.into_iter().find(|m| m.model_code.eq_ignore_ascii_case(model_code))
}

/// Search for models matching a partial name or code
pub fn search_models(query: &str) -> Vec<SamsungModel> {
    let db = get_samsung_database();
    let q = query.to_lowercase();
    db.into_iter().filter(|m| {
        m.model_code.to_lowercase().contains(&q) ||
        m.marketing_name.to_lowercase().contains(&q) ||
        m.chipset.to_lowercase().contains(&q)
    }).collect()
}

/// Get all unique models in the database
pub fn list_all_models() -> Vec<SamsungModel> {
    get_samsung_database()
}
