use crate::frp::database::{TecnoModel, TecnoFrpMethod};

/// Get the Infinix FRP device database containing 35 models across Hot, Note, Smart, Zero, and GT series in Kenya.
pub fn get_infinix_database() -> Vec<TecnoModel> {
    vec![
        // ==================== HOT SERIES (11 models) ====================
        TecnoModel {
            marketing_name: "Infinix Hot 40 Pro".into(),
            series: "Hot".into(),
            chipset: "MediaTek Helio G99 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "XOS 13.5".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Helio G99 flagship Hot series model. MTK Auth bypass required for Brom Mode DA erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 40".into(),
            series: "Hot".into(),
            chipset: "MediaTek Helio G88 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "XOS 13.5".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Helio G88. Brom Mode FRP partition erase works cleanly via volume keys + USB connection.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 40i".into(),
            series: "Hot".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into(), "XOS 13.0".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Unisoc T606 budget model. SPD Bootloader FRP erase is instant via Spreadtrum protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 30".into(),
            series: "Hot".into(),
            chipset: "MediaTek Helio G88 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G88. Very popular gaming phone in Nairobi colleges. Brom mode FRP bypass 100% effective.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 30i".into(),
            series: "Hot".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12".into(), "XOS 10.6".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Unisoc T606. Supports direct SPD Bootloader partition erase or SIM PIN notification trick.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 30 Play".into(),
            series: "Hot".into(),
            chipset: "MediaTek Helio G37 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-12".into()),
            notes: Some("6000mAh battery model. Direct MediaTek Brom exploit removes FRP verification.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 20 5G".into(),
            series: "Hot".into(),
            chipset: "MediaTek Dimensity 810 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("Dimensity 810 5G chipset. Requires MTK SLA Auth bypass before preloader FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 20".into(),
            series: "Hot".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2023-09".into()),
            notes: Some("Helio G85. Brom Mode erase FRP partition works reliably without auth restrictions.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 20i".into(),
            series: "Hot".into(),
            chipset: "MediaTek Helio G25 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Helio G25 Android 12 Go. Very fast FRP removal via MTK Client Brom protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 12 Play".into(),
            series: "Hot".into(),
            chipset: "MediaTek Helio P35 (MT6765)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["11".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-05".into()),
            notes: Some("Helio P35 model. Common repair shop device in Kenya with straightforward Brom exploit.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Hot 11 Play".into(),
            series: "Hot".into(),
            chipset: "MediaTek Helio G35 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["11".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2022-12".into()),
            notes: Some("Helio G35. Older Hot series model with 100% success rate on MediaTek Brom FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== NOTE SERIES (10 models) ====================
        TecnoModel {
            marketing_name: "Infinix Note 40 Pro+ 5G".into(),
            series: "Note".into(),
            chipset: "MediaTek Dimensity 7020 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["14".into(), "XOS 14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Dimensity 7020 flagship with 100W fast charging. Requires MTK Auth SLA bypass for Brom erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 40 Pro".into(),
            series: "Note".into(),
            chipset: "MediaTek Helio G99 Ultimate (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["14".into(), "XOS 14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Helio G99 Ultimate. Uses secured preloader; apply MtkAuthBypass before flashing FRP partition.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 40".into(),
            series: "Note".into(),
            chipset: "MediaTek Helio G99 Ultimate (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["14".into(), "XOS 14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Helio G99 Ultimate. MagCharge wireless charging model popular in Nairobi.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 30 Pro".into(),
            series: "Note".into(),
            chipset: "MediaTek Helio G99 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Helio G99 with JBL sound. Brom Mode FRP erase supported without SLA issues on XOS 13.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 30 5G".into(),
            series: "Note".into(),
            chipset: "MediaTek Dimensity 6080 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Dimensity 6080 5G model. Auth bypass recommended before issuing Brom erase commands.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 30".into(),
            series: "Note".into(),
            chipset: "MediaTek Helio G99 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G99 standard Note 30. Direct Brom Mode FRP erase is 100% effective.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 30i".into(),
            series: "Note".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Helio G85 Note 30i AMOLED model. Brom Mode FRP removal works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 12 Pro 5G".into(),
            series: "Note".into(),
            chipset: "MediaTek Dimensity 810 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Dimensity 810 5G. 108MP camera model. Use MTK Auth bypass before erasing FRP.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 12 G96".into(),
            series: "Note".into(),
            chipset: "MediaTek Helio G96 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2023-06".into()),
            notes: Some("Helio G96 processor. Popular Kenya market Note device with AMOLED display.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Note 11".into(),
            series: "Note".into(),
            chipset: "MediaTek Helio G88 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["11".into(), "12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-04".into()),
            notes: Some("Helio G88. Direct MediaTek Brom exploit removes FRP in under 10 seconds.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== SMART SERIES (8 models) ====================
        TecnoModel {
            marketing_name: "Infinix Smart 8 Pro".into(),
            series: "Smart".into(),
            chipset: "MediaTek Helio G36 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Helio G36 budget phone. Brom Mode FRP partition erase works reliably.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Smart 8".into(),
            series: "Smart".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into(), "13 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Unisoc T606. Very high volume entry-level phone in Kenya. SPD Bootloader erase FRP supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Smart 7 Plus".into(),
            series: "Smart".into(),
            chipset: "Unisoc SC9863A1 (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("6000mAh battery Smart 7 Plus. Spreadtrum protocol FRP erase is 100% effective.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Smart 7".into(),
            series: "Smart".into(),
            chipset: "Unisoc SC9863A1 (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("Unisoc SC9863A1 budget device widely sold in Safaricom/Airtel retail shops in Kenya.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Smart 6 Plus".into(),
            series: "Smart".into(),
            chipset: "MediaTek Helio G25 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Helio G25 MediaTek chipset. Brom Mode FRP partition erase works without SLA.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Smart 6".into(),
            series: "Smart".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-05".into()),
            notes: Some("Unisoc SC9863A Android 11 Go. Standard SPD Bootloader FRP partition erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Smart 5 Pro".into(),
            series: "Smart".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-11".into()),
            notes: Some("Unisoc SC9863A budget phone. Instant FRP erase in Spreadtrum bootloader mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Smart 5".into(),
            series: "Smart".into(),
            chipset: "MediaTek Helio A20 (MT6761D)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2022-06".into()),
            notes: Some("Helio A20 quad-core. Older entry-level Infinix phone with 100% Brom Mode erase success.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== ZERO & GT SERIES (6 models) ====================
        TecnoModel {
            marketing_name: "Infinix GT 20 Pro".into(),
            series: "GT".into(),
            chipset: "MediaTek Dimensity 8200 Ultimate (4nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["14".into(), "XOS 14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Dimensity 8200 Ultimate gaming flagship with RGB LED loop. MTK Auth SLA bypass required.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix GT 10 Pro".into(),
            series: "GT".into(),
            chipset: "MediaTek Dimensity 8050 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "XOS 13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Dimensity 8050 cyberpunk design. Requires MTK SLA auth bypass before DA flash.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Zero 30 5G".into(),
            series: "Zero".into(),
            chipset: "MediaTek Dimensity 8020 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Dimensity 8020 with 50MP 4K 60fps front camera. Use MtkAuthBypass for Brom erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Zero 30 4G".into(),
            series: "Zero".into(),
            chipset: "MediaTek Helio G99 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Helio G99 4G Zero series model. Brom Mode FRP partition erase works without auth restrictions.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Zero Ultra".into(),
            series: "Zero".into(),
            chipset: "MediaTek Dimensity 920 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("180W Thunder Charge flagship with 200MP camera. Requires SLA auth bypass in Brom mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Infinix Zero 20".into(),
            series: "Zero".into(),
            chipset: "MediaTek Helio G99 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Helio G99 with 60MP OIS selfie camera. Direct MediaTek Brom exploit removes FRP cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
    ]
}

/// Look up a specific Infinix model by marketing name
pub fn find_infinix_model(name: &str) -> Option<TecnoModel> {
    get_infinix_database()
        .into_iter()
        .find(|m| m.marketing_name.eq_ignore_ascii_case(name))
}

/// Search the Infinix device database by query
pub fn search_infinix_models(query: &str) -> Vec<TecnoModel> {
    let q = query.to_lowercase();
    get_infinix_database()
        .into_iter()
        .filter(|m| {
            m.marketing_name.to_lowercase().contains(&q)
                || m.series.to_lowercase().contains(&q)
                || m.chipset.to_lowercase().contains(&q)
                || m.chipset_family.to_lowercase().contains(&q)
        })
        .collect()
}

/// List all Infinix models
pub fn list_all_infinix_models() -> Vec<TecnoModel> {
    get_infinix_database()
}

/// Filter Infinix models by series ("all", "Hot", "Note", "Smart", "Zero", "GT")
pub fn get_infinix_by_series(series: &str) -> Vec<TecnoModel> {
    if series.eq_ignore_ascii_case("all") {
        get_infinix_database()
    } else {
        get_infinix_database()
            .into_iter()
            .filter(|m| m.series.eq_ignore_ascii_case(series))
            .collect()
    }
}
