use crate::frp::database::{TecnoModel, TecnoFrpMethod};

/// Get the Itel FRP device database containing 35 models across A, P, S, and Vision series in Kenya.
pub fn get_itel_database() -> Vec<TecnoModel> {
    vec![
        // ==================== A SERIES (14 models) ====================
        TecnoModel {
            marketing_name: "Itel A70".into(),
            series: "A".into(),
            chipset: "Unisoc T603 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13 Go".into(), "itelOS 13".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Unisoc T603 budget phone with Dynamic Bar. SPD Bootloader mode FRP erase works instantly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A60s".into(),
            series: "A".into(),
            chipset: "Unisoc SC9863A1 (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Unisoc SC9863A1. Extremely popular entry-level phone in Kenya. Spreadtrum protocol erase FRP.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A60".into(),
            series: "A".into(),
            chipset: "Unisoc SC9832E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Unisoc SC9832E quad-core 4G phone. Direct SPD Bootloader FRP partition erase supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A58 Pro".into(),
            series: "A".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-04".into()),
            notes: Some("Unisoc SC7731E 3G model. Erase FRP partition in SPD Bootloader mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A58".into(),
            series: "A".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-02".into()),
            notes: Some("Unisoc SC7731E Android 11 Go. Standard SPD bootloader FRP erase protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A57".into(),
            series: "A".into(),
            chipset: "Unisoc SC9832E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-10".into()),
            notes: Some("Unisoc SC9832E 4G model. strong evidence band (75) on SPD bootloader FRP reset.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A56 Pro".into(),
            series: "A".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["9.0 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-06".into()),
            notes: Some("Android 9 Go edition. Spreadtrum SPD bootloader FRP erase is instant.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A56".into(),
            series: "A".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["9.0 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-05".into()),
            notes: Some("Older A series budget phone widely used across Kenya rural markets.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A48".into(),
            series: "A".into(),
            chipset: "Unisoc SC9832E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-08".into()),
            notes: Some("SC9832E processor. SPD bootloader partition erase works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A37".into(),
            series: "A".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-04".into()),
            notes: Some("Budget 5.7-inch display model. Standard Spreadtrum FRP removal protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A33 Plus".into(),
            series: "A".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-01".into()),
            notes: Some("Entry-level 1GB RAM phone. SPD Bootloader erase FRP partition supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A27".into(),
            series: "A".into(),
            chipset: "Unisoc SC9832E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-03".into()),
            notes: Some("4000mAh battery SC9832E model. Fast FRP removal via SPD Flash Tool protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A26".into(),
            series: "A".into(),
            chipset: "Unisoc SC9832E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-09".into()),
            notes: Some("5.7-inch SC9832E phone. Erase FRP partition in SPD Bootloader mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel A24 Pro".into(),
            series: "A".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-07".into()),
            notes: Some("Compact 5-inch model. Spreadtrum protocol FRP erase supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== P SERIES (9 models) ====================
        TecnoModel {
            marketing_name: "Itel P55+".into(),
            series: "P".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into(), "itelOS 13".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Unisoc T606 with 45W fast charge and vegan leather. SPD bootloader erase FRP partition supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel P55 5G".into(),
            series: "P".into(),
            chipset: "MediaTek Dimensity 6080 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Dimensity 6080 5G. First 5G Itel phone in Kenya. Use MTK Auth bypass before Brom Mode DA erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel P55".into(),
            series: "P".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Unisoc T606 90Hz display model. Instant FRP bypass via SPD Bootloader protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel P55T".into(),
            series: "P".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["14 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Android 14 Go edition with 6000mAh battery. SPD Bootloader erase FRP partition supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel P40+".into(),
            series: "P".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("7000mAh massive battery P40+. Spreadtrum SPD bootloader FRP erase works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel P40".into(),
            series: "P".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("6000mAh battery SC9863A model. Very common phone in Kenya rural/urban retail shops.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel P38 Pro 5G".into(),
            series: "P".into(),
            chipset: "MediaTek Dimensity 700 (7nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["11".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-05".into()),
            notes: Some("Dimensity 700 MediaTek chipset. MTK SLA Auth bypass required before Brom Mode FRP reset.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel P38".into(),
            series: "P".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-04".into()),
            notes: Some("15W fast charging budget 3G model. SPD Bootloader mode FRP partition erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel P37 Pro".into(),
            series: "P".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10".into(), "10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-12".into()),
            notes: Some("5000mAh SC9863A 4G phone. Erase FRP partition in SPD Bootloader mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== S SERIES (8 models) ====================
        TecnoModel {
            marketing_name: "Itel S24".into(),
            series: "S".into(),
            chipset: "MediaTek Helio G91 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Helio G91 with 108MP camera. MediaTek Brom Mode FRP partition erase works cleanly without SLA.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel S23+".into(),
            series: "S".into(),
            chipset: "Unisoc T616 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into(), "itelOS 13".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Unisoc T616 curved AMOLED flagship Itel model in Kenya. SPD Bootloader FRP erase supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel S23".into(),
            series: "S".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Unisoc T606 color-changing back panel. Highly popular youth model in Nairobi.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel S18 Pro".into(),
            series: "S".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Selfie-focused S18 Pro. SPD bootloader erase FRP partition works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel S18".into(),
            series: "S".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-06".into()),
            notes: Some("Unisoc SC9863A Android 12 Go. Standard SPD Bootloader FRP partition erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel S17".into(),
            series: "S".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-10".into()),
            notes: Some("SC7731E 3G smile-capture camera phone. Instant Spreadtrum bootloader FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel S16 Pro".into(),
            series: "S".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-07".into()),
            notes: Some("6.6-inch punch-hole display SC9863A phone. Spreadtrum SPD bootloader FRP reset.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel S16".into(),
            series: "S".into(),
            chipset: "Unisoc SC7731E (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-05".into()),
            notes: Some("Older S16 series model. strong evidence band (75) on SPD bootloader FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== VISION SERIES (4 models) ====================
        TecnoModel {
            marketing_name: "Itel Vision 3 Plus".into(),
            series: "Vision".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-04".into()),
            notes: Some("Unisoc T606 90Hz 6000mAh battery phone. SPD Bootloader mode FRP erase supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel Vision 3".into(),
            series: "Vision".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-02".into()),
            notes: Some("SC9863A 18W fast charge model. Erase FRP partition in SPD bootloader mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel Vision 2S".into(),
            series: "Vision".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-10".into()),
            notes: Some("5000mAh SC9863A phone. SPD bootloader erase FRP partition works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Itel Vision 2".into(),
            series: "Vision".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["10 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2022-06".into()),
            notes: Some("6.6-inch SC9863A model. Standard Spreadtrum protocol FRP removal.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
    ]
}

/// Look up a specific Itel model by marketing name
pub fn find_itel_model(name: &str) -> Option<TecnoModel> {
    get_itel_database()
        .into_iter()
        .find(|m| m.marketing_name.eq_ignore_ascii_case(name))
}

/// Search the Itel device database by query
pub fn search_itel_models(query: &str) -> Vec<TecnoModel> {
    let q = query.to_lowercase();
    get_itel_database()
        .into_iter()
        .filter(|m| {
            m.marketing_name.to_lowercase().contains(&q)
                || m.series.to_lowercase().contains(&q)
                || m.chipset.to_lowercase().contains(&q)
                || m.chipset_family.to_lowercase().contains(&q)
        })
        .collect()
}

/// List all Itel models
pub fn list_all_itel_models() -> Vec<TecnoModel> {
    get_itel_database()
}

/// Filter Itel models by series ("all", "A", "P", "S", "Vision")
pub fn get_itel_by_series(series: &str) -> Vec<TecnoModel> {
    if series.eq_ignore_ascii_case("all") {
        get_itel_database()
    } else {
        get_itel_database()
            .into_iter()
            .filter(|m| m.series.eq_ignore_ascii_case(series))
            .collect()
    }
}
