use crate::frp::database::{TecnoModel, TecnoFrpMethod};

/// Get the Q3 FRP device database containing 60 models across Xiaomi, Redmi, POCO, OPPO, Realme, Vivo, and Honor in Kenya.
pub fn get_q3_database() -> Vec<TecnoModel> {
    vec![
        // ==================== XIAOMI / REDMI / POCO (25 models) ====================
        TecnoModel {
            marketing_name: "Redmi Note 13 Pro+ 5G".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Dimensity 7200 Ultra (4nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into(), "HyperOS".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Dimensity 7200 Ultra flagship. Xiaomi HyperOS / MIUI 14. Requires MTK SLA Auth bypass in Brom Mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 13 Pro 5G".into(),
            series: "Redmi".into(),
            chipset: "Qualcomm Snapdragon 7s Gen 2 (4nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "14".into(), "HyperOS".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
                TecnoFrpMethod::DeviceProvisioning,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Snapdragon 7s Gen 2. EDL 9008 Mode FRP erase or TalkBack accessibility shortcut to Settings.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 13 Pro 4G".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio G99 Ultra (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Helio G99 Ultra with 200MP camera. MTK Auth SLA bypass required before Brom FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 13 5G".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Dimensity 6080 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Dimensity 6080 5G. Very popular mid-ranger in Kenya. Brom Mode erase supported with SLA auth.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 13 4G".into(),
            series: "Redmi".into(),
            chipset: "Qualcomm Snapdragon 685 (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Snapdragon 685 4G model. TalkBack gesture navigation -> Chrome -> Disable Google Play Services.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 12 Pro 5G".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Dimensity 1080 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into(), "13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Dimensity 1080 5G. Use MTK SLA auth bypass before flashing FRP partition in Brom mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 12 4G".into(),
            series: "Redmi".into(),
            chipset: "Qualcomm Snapdragon 685 (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Snapdragon 685 AMOLED 120Hz model. High-volume Xiaomi device in Nairobi.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 12S".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio G96 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G96 processor. Brom Mode FRP partition erase works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 11 Pro 5G".into(),
            series: "Redmi".into(),
            chipset: "Qualcomm Snapdragon 695 5G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Snapdragon 695 5G. Standard Android TalkBack gesture bypass works on MIUI 13/14.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi Note 11".into(),
            series: "Redmi".into(),
            chipset: "Qualcomm Snapdragon 680 4G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("Snapdragon 680. One of the most popular Xiaomi models in Sub-Saharan Africa.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi 13C".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Helio G85 best-selling budget phone in Kenya. Direct Brom Mode FRP erase is supported (evidence band 80, lab-gated).".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi 12C".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G85 budget model. Brom Mode FRP partition erase works without SLA auth.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi 12".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio G88 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Helio G88 glass-back budget phone. Fast FRP removal via MediaTek Brom exploit.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi A3".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio G36 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["14 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Android 14 Go edition with Halo camera design. Direct Brom Mode erase FRP partition.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi A2+".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio G36 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G36 fingerprint model. Brom Mode FRP removal is instant and reliable.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi A2".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio G36 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G36 entry-level phone. Very popular in Kenyan Safaricom/Airtel bundles.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Redmi A1+".into(),
            series: "Redmi".into(),
            chipset: "MediaTek Helio A22 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-09".into()),
            notes: Some("Helio A22 quad-core. strong evidence band (80) on MediaTek Brom FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "POCO X6 Pro 5G".into(),
            series: "POCO".into(),
            chipset: "MediaTek Dimensity 8300 Ultra (4nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["14".into(), "HyperOS".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Dimensity 8300 Ultra flagship killer. Requires MTK SLA Auth bypass before DA flash.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "POCO X6 5G".into(),
            series: "POCO".into(),
            chipset: "Qualcomm Snapdragon 7s Gen 2 (4nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "14".into(), "HyperOS".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Snapdragon 7s Gen 2. EDL 9008 Mode or TalkBack browser bypass to disable Google Play Services.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "POCO M6 Pro 4G".into(),
            series: "POCO".into(),
            chipset: "MediaTek Helio G99 Ultra (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Helio G99 Ultra AMOLED 120Hz model. Use MTK Auth bypass before Brom FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "POCO M5".into(),
            series: "POCO".into(),
            chipset: "MediaTek Helio G99 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2023-12".into()),
            notes: Some("Helio G99 faux-leather finish model. Brom Mode FRP erase supported cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "POCO C65".into(),
            series: "POCO".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Helio G85 entry-level POCO. Same hardware architecture as Redmi 13C. Brom erase instant.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "POCO C55".into(),
            series: "POCO".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Helio G85 budget phone. Direct MediaTek Brom exploit removes FRP verification.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Xiaomi 14".into(),
            series: "Xiaomi".into(),
            chipset: "Qualcomm Snapdragon 8 Gen 3 (4nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["14".into(), "HyperOS".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Snapdragon 8 Gen 3 Leica flagship. Uses TalkBack accessibility shortcut or EDL authorization.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Xiaomi 13T".into(),
            series: "Xiaomi".into(),
            chipset: "MediaTek Dimensity 8200 Ultra (4nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into(), "HyperOS".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Dimensity 8200 Ultra. Requires SLA Auth bypass before executing DA Brom FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },

        // ==================== OPPO (12 models) ====================
        TecnoModel {
            marketing_name: "OPPO Reno11 5G".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Dimensity 7050 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["14".into(), "ColorOS 14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Dimensity 7050 ColorOS 14. Apply MTK Auth bypass to disable preloader SLA before FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO Reno11 F 5G".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Dimensity 7050 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["14".into(), "ColorOS 14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Dimensity 7050 IP65 rated model. High-demand OPPO phone in Kenya. Brom erase supported with auth bypass.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO Reno10 5G".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Dimensity 7050 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Dimensity 7050 telephoto portrait model. Auth bypass required for DA flash protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A78 4G".into(),
            series: "OPPO".into(),
            chipset: "Qualcomm Snapdragon 680 4G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "ColorOS 13.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
                TecnoFrpMethod::DeviceProvisioning,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Snapdragon 680 67W SuperVOOC model. TalkBack accessibility gesture opens ColorOS browser.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A58 4G".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "ColorOS 13.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Helio G85 FHD+ screen model. Brom Mode FRP partition erase works cleanly without SLA.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A38".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "ColorOS 13.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G85 90Hz display phone. Direct MediaTek Brom exploit removes FRP in seconds.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A18".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "ColorOS 13.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Helio G85 budget OPPO device in Kenya. strong evidence band (80) on MediaTek Brom FRP erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A17".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Helio G35 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into(), "ColorOS 12.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Helio G35 leather-texture back phone. Direct Brom Mode erase FRP partition supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A17k".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Helio G35 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into(), "ColorOS 12.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("Helio G35 single camera entry-level model. Brom Mode FRP removal works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A57 4G".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Helio G35 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Helio G35 33W fast charge model. Fast FRP erase via MediaTek Client protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A16".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Helio G35 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["11".into(), "ColorOS 11.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-05".into()),
            notes: Some("Helio G35 5000mAh battery phone. Direct Brom Mode FRP erase is supported (evidence band 80, lab-gated).".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "OPPO A16k".into(),
            series: "OPPO".into(),
            chipset: "MediaTek Helio G35 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["11".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-04".into()),
            notes: Some("Older budget OPPO A16 series phone. strong evidence band (80) on MediaTek Brom FRP reset.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== REALME (9 models) ====================
        TecnoModel {
            marketing_name: "Realme 12 Pro+ 5G".into(),
            series: "Realme".into(),
            chipset: "Qualcomm Snapdragon 7s Gen 2 (4nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["14".into(), "Realme UI 5.0".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Snapdragon 7s Gen 2 periscope camera flagship. Use TalkBack accessibility shortcut or EDL mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Realme 11 4G".into(),
            series: "Realme".into(),
            chipset: "MediaTek Helio G99 (6nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "Realme UI 4.0".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Helio G99 AMOLED 90Hz model. MediaTek Brom Mode FRP partition erase works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Realme C67".into(),
            series: "Realme".into(),
            chipset: "Qualcomm Snapdragon 685 (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["14".into(), "Realme UI".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Snapdragon 685 108MP camera model. Very popular Realme phone in Nairobi. TalkBack browser bypass.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Realme C53".into(),
            series: "Realme".into(),
            chipset: "Unisoc T612 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into(), "Realme UI T".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Unisoc T612 Mini Capsule design. SPD Bootloader mode FRP erase is supported (evidence band 75, lab-gated).".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Realme C51".into(),
            series: "Realme".into(),
            chipset: "Unisoc T612 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into(), "Realme UI T".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Unisoc T612 33W fast charge budget model. Instant FRP erase in SPD Bootloader mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Realme C33".into(),
            series: "Realme".into(),
            chipset: "Unisoc T612 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12".into(), "Realme UI S".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("Unisoc T612 50MP camera phone. SPD Bootloader mode FRP partition erase supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Realme C30s".into(),
            series: "Realme".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Unisoc SC9863A side-fingerprint entry phone. Spreadtrum SPD bootloader FRP reset.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Realme C30".into(),
            series: "Realme".into(),
            chipset: "Unisoc T612 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-06".into()),
            notes: Some("Unisoc T612 vertical stripe design. Fast FRP removal via SPD Flash Tool protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Realme Narzo N53".into(),
            series: "Realme".into(),
            chipset: "Unisoc T612 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Unisoc T612 slim Narzo series model. Erase FRP partition in SPD Bootloader mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== VIVO (8 models) ====================
        TecnoModel {
            marketing_name: "Vivo V30 5G".into(),
            series: "Vivo".into(),
            chipset: "Qualcomm Snapdragon 7 Gen 3 (4nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["14".into(), "Funtouch OS 14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Snapdragon 7 Gen 3 Aura Light flagship. TalkBack gesture navigation -> Chrome -> Disable Play Services.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Vivo V29 5G".into(),
            series: "Vivo".into(),
            chipset: "Qualcomm Snapdragon 778G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Snapdragon 778G curved AMOLED display. Popular high-end Vivo in Kenya.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Vivo V29e".into(),
            series: "Vivo".into(),
            chipset: "Qualcomm Snapdragon 695 5G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "Funtouch OS 13".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Snapdragon 695 5G slim body model. Standard Android TalkBack gesture bypass.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Vivo Y36 4G".into(),
            series: "Vivo".into(),
            chipset: "Qualcomm Snapdragon 680 4G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Snapdragon 680 crystal glass design. TalkBack browser bypass or EDL authorization.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Vivo Y27 4G".into(),
            series: "Vivo".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "Funtouch OS 13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G85 44W flash charge model. Brom Mode FRP partition erase works cleanly without SLA.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Vivo Y17s".into(),
            series: "Vivo".into(),
            chipset: "MediaTek Helio G85 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Helio G85 entry-level Y series. Very popular Vivo device in Kenyan mobile shops. Brom erase instant.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Vivo Y16".into(),
            series: "Vivo".into(),
            chipset: "MediaTek Helio P35 (MT6765)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-09".into()),
            notes: Some("Helio P35 2.5D curvature model. Direct Brom Mode erase FRP partition supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Vivo Y02t".into(),
            series: "Vivo".into(),
            chipset: "MediaTek Helio P35 (MT6765)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Helio P35 Android 13 Go edition. Fast FRP removal via MediaTek Brom exploit.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== HONOR (6 models) ====================
        TecnoModel {
            marketing_name: "Honor 90 5G".into(),
            series: "Honor".into(),
            chipset: "Qualcomm Snapdragon 7 Gen 1 Accelerated (4nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "MagicOS 7.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Snapdragon 7 Gen 1 with 200MP camera. TalkBack accessibility gesture opens Chrome to disable setup wizard.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Honor 90 Lite".into(),
            series: "Honor".into(),
            chipset: "MediaTek Dimensity 6020 (7nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "MagicOS 7.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::MtkAuthBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Dimensity 6020 5G 100MP camera model. Use MTK Auth bypass before Brom FRP partition erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: true,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Honor X9b".into(),
            series: "Honor".into(),
            chipset: "Qualcomm Snapdragon 6 Gen 1 (4nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Snapdragon 6 Gen 1 anti-drop display model. Popular mid-tier Honor phone in Nairobi.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Honor X8b".into(),
            series: "Honor".into(),
            chipset: "Qualcomm Snapdragon 680 4G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "MagicOS 7.2".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Snapdragon 680 AMOLED 2000-nits display model. Standard Android TalkBack gesture bypass works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Honor X7b".into(),
            series: "Honor".into(),
            chipset: "Qualcomm Snapdragon 680 4G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["13".into(), "MagicOS 7.2".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Snapdragon 680 6000mAh battery phone. TalkBack accessibility shortcut allows launching Chrome.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Honor X6a".into(),
            series: "Honor".into(),
            chipset: "MediaTek Helio G36 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["13".into(), "MagicOS 7.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Helio G36 budget Honor phone in Kenya. Direct MediaTek Brom exploit removes FRP in under 10 seconds.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
    ]
}

/// Look up a specific Q3 model by marketing name
pub fn find_q3_model(name: &str) -> Option<TecnoModel> {
    get_q3_database()
        .into_iter()
        .find(|m| m.marketing_name.eq_ignore_ascii_case(name))
}

/// Search the Q3 device database by query
pub fn search_q3_models(query: &str) -> Vec<TecnoModel> {
    let q = query.to_lowercase();
    get_q3_database()
        .into_iter()
        .filter(|m| {
            m.marketing_name.to_lowercase().contains(&q)
                || m.series.to_lowercase().contains(&q)
                || m.chipset.to_lowercase().contains(&q)
                || m.chipset_family.to_lowercase().contains(&q)
        })
        .collect()
}

/// List all Q3 models
pub fn list_all_q3_models() -> Vec<TecnoModel> {
    get_q3_database()
}

/// Filter Q3 models by brand/series ("all", "Xiaomi", "Redmi", "POCO", "OPPO", "Realme", "Vivo", "Honor")
pub fn get_q3_by_brand(brand: &str) -> Vec<TecnoModel> {
    if brand.eq_ignore_ascii_case("all") {
        get_q3_database()
    } else {
        get_q3_database()
            .into_iter()
            .filter(|m| m.series.eq_ignore_ascii_case(brand))
            .collect()
    }
}
