use crate::frp::database::{TecnoModel, TecnoFrpMethod};

/// Get the Q4 FRP device database containing 33 models across Nokia, Moto, Huawei, Sony, Pixel, and Credit-locked devices in Kenya.
pub fn get_q4_database() -> Vec<TecnoModel> {
    vec![
        // ==================== NOKIA (10 models) ====================
        TecnoModel {
            marketing_name: "Nokia G21".into(),
            series: "Nokia".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Unisoc T606 Bootloader FRP erase supported via SPD flash tool protocol. Popular in Kenya market.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia G20".into(),
            series: "Nokia".into(),
            chipset: "MediaTek Helio G35 (MT6765G)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("MediaTek Helio G35 supports direct Brom Mode FRP erase via volume keys + USB cable.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia G10".into(),
            series: "Nokia".into(),
            chipset: "MediaTek Helio G25 (MT6762G)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["11".into(), "12".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Helio G25 Brom exploit works reliably without SLA authentication.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia C30".into(),
            series: "Nokia".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11".into(), "11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("Android 11 Go edition. SPD Bootloader erase FRP partition is instant.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia C21 Plus".into(),
            series: "Nokia".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("Unisoc SC9863A budget device widely available in Safaricom/Airtel shops in Kenya.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia C22".into(),
            series: "Nokia".into(),
            chipset: "Unisoc SC9863A1 (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Android 13 Go edition. Spreadtrum protocol erase FRP partition supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia X20".into(),
            series: "Nokia".into(),
            chipset: "Qualcomm Snapdragon 480 5G (8nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
                TecnoFrpMethod::DeviceProvisioning,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("Snapdragon 480 5G. Use TalkBack accessibility shortcut to open settings and disable setup wizard.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia X10".into(),
            series: "Nokia".into(),
            chipset: "Qualcomm Snapdragon 480 5G (8nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Qualcomm device. SIM PIN notification shade bypass works on Android 11/12 builds.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia 5.4".into(),
            series: "Nokia".into(),
            chipset: "Qualcomm Snapdragon 662 (11nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["10".into(), "11".into(), "12".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::AccountManagerLaunch,
            ],
            max_security_patch: Some("2023-09".into()),
            notes: Some("Snapdragon 662 mid-ranger. Google Account Manager login activity launch works on Android 10/11.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia 3.4".into(),
            series: "Nokia".into(),
            chipset: "Qualcomm Snapdragon 460 (11nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["10".into(), "11".into(), "12".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2023-06".into()),
            notes: Some("Snapdragon 460. Popular Nokia model in Nairobi electronics shops.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== MOTOROLA / MOTO (7 models) ====================
        TecnoModel {
            marketing_name: "Moto E20".into(),
            series: "Moto".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SimPinBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-10".into()),
            notes: Some("Unisoc T606 Android 11 Go. SPD Bootloader mode FRP erase is 100% effective.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Moto E32".into(),
            series: "Moto".into(),
            chipset: "Unisoc T606 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11".into(), "12".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Unisoc T606 chipset. SPD Flash Tool protocol or TalkBack browser bypass.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Moto E40".into(),
            series: "Moto".into(),
            chipset: "Unisoc T700 (12nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["11".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SimPinBypass,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Unisoc T700 processor. Enter Spreadtrum bootloader for direct partition erase.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Moto G22".into(),
            series: "Moto".into(),
            chipset: "MediaTek Helio G37 (12nm)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("MediaTek Helio G37. Brom Mode FRP erase supported via MTK client protocol.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Moto G32".into(),
            series: "Moto".into(),
            chipset: "Qualcomm Snapdragon 680 4G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
                TecnoFrpMethod::DeviceProvisioning,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Snapdragon 680 4G. Use TalkBack gestures to access Chrome and disable Google Play Services.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Moto G52".into(),
            series: "Moto".into(),
            chipset: "Qualcomm Snapdragon 680 4G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Snapdragon 680. Mid-tier Motorola model sold by authorized dealers in Kenya.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Moto G60".into(),
            series: "Moto".into(),
            chipset: "Qualcomm Snapdragon 732G (8nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["11".into(), "12".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2023-12".into()),
            notes: Some("Snapdragon 732G. High-demand Motorola phone in Nairobi with 108MP camera.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== HUAWEI (6 models) ====================
        TecnoModel {
            marketing_name: "Huawei Y9a".into(),
            series: "Huawei".into(),
            chipset: "MediaTek Helio G80 (MT6769V/CU)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["10".into(), "EMUI 10.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::EmergencyDialerBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2023-08".into()),
            notes: Some("MediaTek Helio G80. Brom Mode FRP erase bypasses EMUI Huawei ID and Google FRP.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Huawei Y7a".into(),
            series: "Huawei".into(),
            chipset: "HiSilicon Kirin 710A (14nm)".into(),
            chipset_family: "Kirin".into(),
            android_versions: vec!["10".into(), "EMUI 10.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::EmergencyDialerBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2023-06".into()),
            notes: Some("Kirin 710A chipset. Emergency call + calendar notification trick allows reaching settings.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Huawei P30 Lite".into(),
            series: "Huawei".into(),
            chipset: "HiSilicon Kirin 710 (12nm)".into(),
            chipset_family: "Kirin".into(),
            android_versions: vec!["9.0".into(), "10".into()],
            supported_methods: vec![
                TecnoFrpMethod::EmergencyDialerBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::AccountManagerLaunch,
            ],
            max_security_patch: Some("2022-12".into()),
            notes: Some("Kirin 710. Extremely common Huawei model in Kenya. Safe Mode recovery bypass also supported.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Huawei Nova 7i".into(),
            series: "Huawei".into(),
            chipset: "HiSilicon Kirin 810 (7nm)".into(),
            chipset_family: "Kirin".into(),
            android_versions: vec!["10".into(), "EMUI 10.0.1".into()],
            supported_methods: vec![
                TecnoFrpMethod::EmergencyDialerBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
            ],
            max_security_patch: Some("2023-05".into()),
            notes: Some("Kirin 810. Uses EMUI 10 recovery mode reset or emergency dialer bypass.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Huawei Y9s".into(),
            series: "Huawei".into(),
            chipset: "HiSilicon Kirin 710F (12nm)".into(),
            chipset_family: "Kirin".into(),
            android_versions: vec!["9.0".into(), "10".into()],
            supported_methods: vec![
                TecnoFrpMethod::EmergencyDialerBypass,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2022-11".into()),
            notes: Some("Kirin 710F with pop-up camera. SIM PIN swap technique opens notification shade.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Huawei Y6s".into(),
            series: "Huawei".into(),
            chipset: "MediaTek Helio P35 (MT6765)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["9.0".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2022-08".into()),
            notes: Some("Helio P35 MediaTek model. Direct Brom Mode erase FRP partition works cleanly.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== SONY (3 models) ====================
        TecnoModel {
            marketing_name: "Sony Xperia 10 IV".into(),
            series: "Sony".into(),
            chipset: "Qualcomm Snapdragon 695 5G (6nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["12".into(), "13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("Snapdragon 695 5G. Open browser via TalkBack privacy policy link to install bypass helper.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Sony Xperia 10 III".into(),
            series: "Sony".into(),
            chipset: "Qualcomm Snapdragon 690 5G (8nm)".into(),
            chipset_family: "Qualcomm".into(),
            android_versions: vec!["11".into(), "12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SimPinBypass,
            ],
            max_security_patch: Some("2023-11".into()),
            notes: Some("Snapdragon 690 5G. Standard Android TalkBack gesture bypass works on Xperia UI.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Sony Xperia L4".into(),
            series: "Sony".into(),
            chipset: "MediaTek Helio P22 (MT6762)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["9.0".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::QuickShortcutMaker,
            ],
            max_security_patch: Some("2022-04".into()),
            notes: Some("MediaTek Helio P22. Direct Brom Mode FRP partition erase supported via MTK client.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== GOOGLE PIXEL (4 models) ====================
        TecnoModel {
            marketing_name: "Google Pixel 6a".into(),
            series: "Pixel".into(),
            chipset: "Google Tensor (5nm)".into(),
            chipset_family: "Exynos".into(),
            android_versions: vec!["12".into(), "13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
                TecnoFrpMethod::DeviceProvisioning,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Google Tensor (Exynos-based architecture). Use TalkBack accessibility shortcut to launch Chrome and disable Google Play Services.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Google Pixel 6".into(),
            series: "Pixel".into(),
            chipset: "Google Tensor (5nm)".into(),
            chipset_family: "Exynos".into(),
            android_versions: vec!["12".into(), "13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-04".into()),
            notes: Some("Google Tensor flagship. Popular imported device in Nairobi electronics market.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Google Pixel 7".into(),
            series: "Pixel".into(),
            chipset: "Google Tensor G2 (4nm)".into(),
            chipset_family: "Exynos".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Google Tensor G2. Requires latest TalkBack Braille keyboard or voice command shortcut.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Google Pixel 7a".into(),
            series: "Pixel".into(),
            chipset: "Google Tensor G2 (4nm)".into(),
            chipset_family: "Exynos".into(),
            android_versions: vec!["13".into(), "14".into()],
            supported_methods: vec![
                TecnoFrpMethod::TalkBackBypass,
                TecnoFrpMethod::SettingsAccess,
                TecnoFrpMethod::BrowserDownloadBypass,
                TecnoFrpMethod::SetupWizardDisable,
            ],
            max_security_patch: Some("2024-05".into()),
            notes: Some("Pixel 7a. Accessible via TalkBack tutorial menu -> Help & Feedback -> Open Web Link.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },

        // ==================== CREDIT LOCK / FINANCED DEVICES (3 models) ====================
        TecnoModel {
            marketing_name: "Samsung Galaxy A04 (M-Kopa Edition)".into(),
            series: "Credit".into(),
            chipset: "MediaTek Helio P35 (MT6765)".into(),
            chipset_family: "MediaTek".into(),
            android_versions: vec!["12".into(), "13".into()],
            supported_methods: vec![
                TecnoFrpMethod::MtkBromErase,
                TecnoFrpMethod::SetupWizardDisable,
                TecnoFrpMethod::SetupWizardUninstall,
                TecnoFrpMethod::DeviceProvisioning,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-02".into()),
            notes: Some("M-Kopa Asset Finance locked device in Kenya. Requires disabling MDM/Trustonic packages after FRP bypass via ADB or Brom Mode.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Tecno Pop 7 (Watu Credit Lock)".into(),
            series: "Credit".into(),
            chipset: "Unisoc SC9863A1 (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["12 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::SetupWizardDisable,
                TecnoFrpMethod::SetupWizardUninstall,
                TecnoFrpMethod::DeviceProvisioning,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-01".into()),
            notes: Some("Watu Credit locked Tecno Pop 7 in Kenya. Erase FRP partition in SPD Bootloader, then disable Watu finance lock apk via ADB.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
        TecnoModel {
            marketing_name: "Nokia C22 (PayJoy Lock)".into(),
            series: "Credit".into(),
            chipset: "Unisoc SC9863A (28nm)".into(),
            chipset_family: "Spreadtrum".into(),
            android_versions: vec!["13 Go".into()],
            supported_methods: vec![
                TecnoFrpMethod::SpdBootloaderErase,
                TecnoFrpMethod::SetupWizardDisable,
                TecnoFrpMethod::SetupWizardUninstall,
                TecnoFrpMethod::DeviceProvisioning,
                TecnoFrpMethod::SettingsAccess,
            ],
            max_security_patch: Some("2024-03".into()),
            notes: Some("PayJoy financing lock edition. SPD bootloader erase FRP + uninstall PayJoy admin package for user 0.".into()),
            requires_preauthorized_adb: false,
            has_mtk_auth: false,
            available_in_kenya: true,
        },
    ]
}

/// Look up a specific Q4 model by marketing name
pub fn find_q4_model(name: &str) -> Option<TecnoModel> {
    get_q4_database()
        .into_iter()
        .find(|m| m.marketing_name.eq_ignore_ascii_case(name))
}

/// Search the Q4 device database by query
pub fn search_q4_models(query: &str) -> Vec<TecnoModel> {
    let q = query.to_lowercase();
    get_q4_database()
        .into_iter()
        .filter(|m| {
            m.marketing_name.to_lowercase().contains(&q)
                || m.series.to_lowercase().contains(&q)
                || m.chipset.to_lowercase().contains(&q)
                || m.chipset_family.to_lowercase().contains(&q)
        })
        .collect()
}

/// List all Q4 models
pub fn list_all_q4_models() -> Vec<TecnoModel> {
    get_q4_database()
}

/// Filter Q4 models by brand/series ("all", "Nokia", "Moto", "Huawei", "Sony", "Pixel", "Credit")
pub fn get_q4_by_brand(brand: &str) -> Vec<TecnoModel> {
    if brand.eq_ignore_ascii_case("all") {
        get_q4_database()
    } else {
        get_q4_database()
            .into_iter()
            .filter(|m| m.series.eq_ignore_ascii_case(brand))
            .collect()
    }
}
